# Generated by Django 4.1.1 on 2022-11-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestra', models.CharField(max_length=50)),
                ('palestrantes', models.CharField(max_length=50)),
                ('curriculo', models.CharField(max_length=50)),
                ('dia_hora', models.DateTimeField()),
                ('sala', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Palestra',
                'verbose_name_plural': 'Palestras',
            },
        ),
    ]
